export const ESPECIALIDADES = [
  'Clínico Geral',
  'Intensivista',
  'Ortopedista',
  'Cardiologista',
  'Pediatra',
  'Ginecologista',
  'Dermatologista',
  'Neurologista',
  'Oftalmologista',
  'Psiquiatra',
  'Cirurgião Geral',
  'Anestesista',
  'Urologista',
  'Endocrinologista',
  'Gastroenterologista',
  'Otorrinolaringologista',
  'Pneumologista',
  'Nefrologista',
  'Infectologista',
  'Geriatra',
]
